import type { Medicine } from './types';

export const MEDICINES: Medicine[] = [
  {
    id: 'm1',
    name: 'Crocin Advance',
    genericName: 'Paracetamol 500mg',
    manufacturer: 'GSK',
    price: 30,
    discountPrice: 25,
    dosageForm: 'Tablet',
    strength: '500mg',
    packSize: '15 tablets',
    category: 'Pain Relief',
    prescription: false,
    description: 'Used for fever and mild to moderate pain relief',
    uses: ['Fever', 'Headache', 'Body Pain'],
    sideEffects: ['Nausea', 'Allergic reactions'],
    inStock: true,
    rating: 4.5,
  },
  {
    id: 'm2',
    name: 'Glycomet GP 1',
    genericName: 'Metformin + Glimepiride',
    manufacturer: 'USV',
    price: 120,
    discountPrice: 98,
    dosageForm: 'Tablet',
    strength: '500mg/1mg',
    packSize: '10 tablets',
    category: 'Diabetes',
    prescription: true,
    description: 'For type 2 diabetes management',
    uses: ['Type 2 Diabetes', 'Blood Sugar Control'],
    sideEffects: ['Hypoglycemia', 'Nausea', 'Diarrhea'],
    inStock: true,
    rating: 4.3,
  },
  {
    id: 'm3',
    name: 'Ecosprin 75',
    genericName: 'Aspirin 75mg',
    manufacturer: 'USV',
    price: 12,
    dosageForm: 'Tablet',
    strength: '75mg',
    packSize: '14 tablets',
    category: 'Heart',
    prescription: true,
    description: 'Low dose aspirin for heart protection',
    uses: ['Heart Protection', 'Blood Thinning'],
    sideEffects: ['Stomach irritation', 'Bleeding'],
    inStock: true,
    rating: 4.6,
  },
  {
    id: 'm4',
    name: 'Thyronorm 50mcg',
    genericName: 'Levothyroxine',
    manufacturer: 'Abbott',
    price: 150,
    discountPrice: 130,
    dosageForm: 'Tablet',
    strength: '50mcg',
    packSize: '30 tablets',
    category: 'Thyroid',
    prescription: true,
    description: 'Thyroid hormone replacement',
    uses: ['Hypothyroidism'],
    sideEffects: ['Weight changes', 'Headache', 'Insomnia'],
    inStock: true,
    rating: 4.4,
  },
  {
    id: 'm5',
    name: 'Shelcal 500',
    genericName: 'Calcium + Vitamin D3',
    manufacturer: 'Torrent',
    price: 175,
    discountPrice: 148,
    dosageForm: 'Tablet',
    strength: '500mg/250IU',
    packSize: '15 tablets',
    category: 'Vitamins',
    prescription: false,
    description: 'Calcium and Vitamin D supplement',
    uses: ['Bone Health', 'Calcium Deficiency', 'Osteoporosis Prevention'],
    sideEffects: ['Constipation', 'Bloating'],
    inStock: true,
    rating: 4.5,
  },
  {
    id: 'm6',
    name: 'Azithral 500',
    genericName: 'Azithromycin',
    manufacturer: 'Alembic',
    price: 85,
    dosageForm: 'Tablet',
    strength: '500mg',
    packSize: '3 tablets',
    category: 'Antibiotics',
    prescription: true,
    description: 'Antibiotic for bacterial infections',
    uses: ['Bacterial Infections', 'Respiratory Infections', 'Skin Infections'],
    sideEffects: ['Diarrhea', 'Nausea', 'Abdominal Pain'],
    inStock: true,
    rating: 4.2,
  },
  {
    id: 'm7',
    name: 'Betadine Ointment',
    genericName: 'Povidone-Iodine',
    manufacturer: 'Win-Medicare',
    price: 60,
    dosageForm: 'Ointment',
    strength: '5% w/w',
    packSize: '15g',
    category: 'Skin Care',
    prescription: false,
    description: 'Antiseptic for cuts and wounds',
    uses: ['Wound Care', 'Skin Infection Prevention'],
    sideEffects: ['Skin irritation', 'Allergic reactions'],
    inStock: true,
    rating: 4.3,
  },
  {
    id: 'm8',
    name: 'Dolo 650',
    genericName: 'Paracetamol 650mg',
    manufacturer: 'Micro Labs',
    price: 28,
    discountPrice: 22,
    dosageForm: 'Tablet',
    strength: '650mg',
    packSize: '15 tablets',
    category: 'Pain Relief',
    prescription: false,
    description: 'Pain and fever relief',
    uses: ['Fever', 'Headache', 'Body Pain', 'Toothache'],
    sideEffects: ['Nausea', 'Liver damage (overdose)'],
    inStock: true,
    rating: 4.7,
  },
  {
    id: 'm9',
    name: 'Telmisartan 40',
    genericName: 'Telmisartan',
    manufacturer: 'Various',
    price: 75,
    discountPrice: 55,
    dosageForm: 'Tablet',
    strength: '40mg',
    packSize: '10 tablets',
    category: 'Heart',
    prescription: true,
    description: 'Blood pressure management',
    uses: ['Hypertension', 'Cardiovascular Protection'],
    sideEffects: ['Dizziness', 'Fatigue', 'Back Pain'],
    inStock: true,
    rating: 4.4,
  },
  {
    id: 'm10',
    name: 'Limcee',
    genericName: 'Vitamin C',
    manufacturer: 'Abbott',
    price: 24,
    dosageForm: 'Tablet',
    strength: '500mg',
    packSize: '15 tablets',
    category: 'Vitamins',
    prescription: false,
    description: 'Vitamin C supplement for immunity',
    uses: ['Immunity Boost', 'Cold Prevention', 'Antioxidant'],
    sideEffects: ['Stomach upset'],
    inStock: true,
    rating: 4.5,
  },
  {
    id: 'm11',
    name: 'Amlip 5',
    genericName: 'Amlodipine 5mg',
    manufacturer: 'Cipla',
    price: 45,
    discountPrice: 35,
    dosageForm: 'Tablet',
    strength: '5mg',
    packSize: '10 tablets',
    category: 'Heart',
    prescription: true,
    description: 'Calcium channel blocker for blood pressure',
    uses: ['Hypertension', 'Angina'],
    sideEffects: ['Swelling', 'Headache', 'Dizziness'],
    inStock: true,
    rating: 4.3,
  },
  {
    id: 'm12',
    name: 'Pan 40',
    genericName: 'Pantoprazole',
    manufacturer: 'Alkem',
    price: 65,
    discountPrice: 50,
    dosageForm: 'Tablet',
    strength: '40mg',
    packSize: '10 tablets',
    category: 'Pain Relief',
    prescription: true,
    description: 'Proton pump inhibitor for acidity',
    uses: ['Acidity', 'GERD', 'Gastric Ulcers'],
    sideEffects: ['Headache', 'Diarrhea', 'Flatulence'],
    inStock: true,
    rating: 4.4,
  },
];

export const MEDICINE_CATEGORIES = [
  'All',
  'Pain Relief',
  'Diabetes',
  'Heart',
  'Thyroid',
  'Vitamins',
  'Antibiotics',
  'Skin Care',
] as const;
